version: '3.3'

services:
  portainerdockerui:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    entrypoint: ["--admin-password=$PASSWORD"]
    networks:
      main-overlay:
        ipv4_address: 10.0.2.121

networks:
  main-overlay:
    external: true

volumes: 
  portainer_data:
  
